### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by wokeboy** [Devilx86/ImpostorModmenu#1]
"App not installed" error whenever downloading apk from mediafire. can't install app whatsoever

**Comment by Devilx86** [comment]
Are you on Android 11?

**Comment by wokeboy** [comment]
Yeah I'm on pixel 3xl running Android 11, That dude in the youtube comments
said he'd email me an apk fixed for android 11 but he hasn't gotten back to
me yet, most likely still asleep bc of time zones.

**Comment by Devilx86** [comment]
On Android 11, for now edit `platformBuildVersionCode` and `android:targetSDKVersion` to 29. Credits to @Digital from polarmods.com for reaching out to me with the bug and its fix, apparently it was suggested to him by @Axey from platinmods.com as a fix for his menu too, so credits to him too. I will fix this in the next modded APK release.

**Comment by wokeboy** [comment]
What's the easiest way to edit this without a PC? All I have right now is a
non rooted phone ):

Appreciate your help by the way it means a lot

**Comment by wokeboy** [comment]
> On Android 11, for now edit `platformBuildVersionCode` and `android:targetSDKVersion` to 29. Credits to Digital from polarmods.com for reaching out to me with the bug and its fix, apparently it was suggested to him by Axey from platinmods.com as a fix for his menu too, so credits to him too. I will fix this in the next modded APK release.

I found where to edit them but I can't find a way to recompile the apk and inject it without a pc unfortunately

**Comment by CAAPIRAI** [comment]
Hi Devilx86,i have problems to dowloand it becuase it says: App not installed. Can you help me pelase. Also i got 8.1.0 android.

**Comment by khanhuypr** [comment]
> Hi Devilx86, tôi có vấn đề để dowloand nó bởi vì nó nói: Ứng dụng không được cài đặt. Bạn có thể giúp tôi pelase. Ngoài ra tôi đã nhận 8.1.0 android.

Delete apps among us original

**Comment by wokeboy** [comment]
> Hi Devilx86,i have problems to dowloand it becuase it says: App not installed. Can you help me pelase. Also i got 8.1.0 android.

also update your phone why are you still on android 8 jesus

**Comment by CAAPIRAI** [comment]
> > Hi Devilx86,i have problems to dowloand it becuase it says: App not installed. Can you help me pelase. Also i got 8.1.0 android.
> 
> also update your phone why are you still on android 8 jesus 

I cant dude,is not my problem

**Comment by CAAPIRAI** [comment]
> > Hi Devilx86, tôi có vấn đề để dowloand nó bởi vì nó nói: Ứng dụng không được cài đặt. Bạn có thể giúp tôi pelase. Ngoài ra tôi đã nhận 8.1.0 android.
> 
> Delete apps among us original

Ok i will try it

**Comment by papaponcho** [comment]
I need help it says app not installed how do I inject I'm on android 9
