### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by T-K0** [Devilx86/ImpostorModmenu#10]
I saw the features your mod includes and they are great. I’m just wondering if you can make a version of your mod for jailbroken iOS devices?

**Comment by Devilx86** [comment]
Hello, Maybe I will in the future, but for now I think you could run it from Bluestacks on IOS

**Comment by Devilx86** [comment]
Sorry, I don't think I will be rewriting this menu to IOS since I have been working on this game for a while now and am already starting to loose interest in it and will be moving on to a different game soon.
