### ISSUE TITLE
Freeze Position Bug

### ISSUE THREAD

**Issue by Redlything** [Devilx86/ImpostorModmenu#15]
Freeze position ain't working like it did in 1.2 now its doesnt freeze people they can still move pls fix this

**Comment by Milionerzy11** [comment]
I aggre i tested it and wont work but when i have old version of that mod menu it works also in older version and in latest freeze all people wont work too all can move

**Comment by Redlything** [comment]
I mean give him a break he made the best mod menu for android pretty sure he can release bug fix I mean even if he  cant I am gonna stick with my 1.2 cuz 1.3 makes me get banned for hacking message all the time...

**Comment by Milionerzy11** [comment]
> I mean give him a break he made the best mod menu for android pretty sure he can release bug fix I mean even if he cant I am gonna stick with my 1.2 cuz 1.3 makes me get banned for hacking message all the time...

Me too

**Comment by Devilx86** [comment]
Thanks, Regarding this, I think the problem you have is Freeze position no longer freezes player, it lets them move but puts them back in their initial position. I will try to fix this in the next update along with the hacking ban issue.

**Comment by Redlything** [comment]
Thanks a lot you are best.I dont have much but still can I support you financily?

**Comment by Devilx86** [comment]
Hey, Thanks but I don't need money, I am sharing this for free in the hope that it helps people learn more and become better. I will add a link to the discord server in the ReadMe

**Comment by Devilx86** [comment]
Old issue, Freeze uses a different method in 1.8 and works fine.
