### ISSUE TITLE
Wallhack bug

### ISSUE THREAD

**Issue by Milionerzy11** [Devilx86/ImpostorModmenu#19]
Wallhack sometimes crashes Among us same thing with spoof message and report dead please fix it

**Comment by Devilx86** [comment]
Sorry but can you figure out a pattern as to when it crashes? if so I can try to fix this but other than that wall hack seems to be working perfectly for me.

**Comment by PapaNoob63** [comment]
it's working fine after 1.3

**Comment by Milionerzy11** [comment]
> Sorry but can you figure out a pattern as to when it crashes? if so I can try to fix this but other than that wall hack seems to be working perfectly for me.

It crashes when i try to open mod menu

**Comment by Milionerzy11** [comment]
> Sorry but can you figure out a pattern as to when it crashes? if so I can try to fix this but other than that wall hack seems to be working perfectly for me.

https://youtu.be/xgs9miJLjPw

**Comment by Devilx86** [comment]
Has wall hack been fixed in 1.5?

**Comment by Milionerzy11** [comment]
Yes issue got fixed
