### ISSUE TITLE
Max Light Range

### ISSUE THREAD

**Issue by anonimity987** [Devilx86/ImpostorModmenu#20]
Max Light range not working! Or is it just me?

**Comment by Milionerzy11** [comment]
> Max Light range not working! Or is it just me?

I think its something with your mod compatibility because for me it works great

**Comment by aljawary** [comment]
Mine also not working

**Comment by PapaNoob63** [comment]
not fix yet. and not working

**Comment by Devilx86** [comment]
Agreed, Max light is a bit buggy, I am not sure when I will fix it tho as its not that big of a feature and I am working on some other features for the next update, but will try to fix it.

**Comment by Devilx86** [comment]
Fixed in 1.7.
