### ISSUE TITLE
Cast Vote Not Working

### ISSUE THREAD

**Issue by PapaNoob63** [Devilx86/ImpostorModmenu#21]
Cast Vote mod not working correctly ,it left one player to vote all player voted but one player left for voting ,fix it please soon in 1.4

**Comment by Devilx86** [comment]
Sorry I don't get you, Do you mean if you select everyone to vote for 'Player 1' and if `Player 1` leaves the game crashes? I have not experienced this before.

**Comment by PapaNoob63** [comment]
> Sorry I don't get you, Do you mean if you select everyone to vote for 'Player 1' and if `Player 1` leaves the game crashes? I have not experienced this before.

bro i said that when u cast vote on ex. red then all the 9 players voted but 1 player are left it happens me most of the time.

**Comment by Devilx86** [comment]
I just tested this now and it does not seem to be the case, cast vote seems to be working fine for me.

**Comment by PapaNoob63** [comment]
> I just tested this now and it does not seem to be the case, cast vote seems to be working fine for me. Please verify and see if you can find a pattern as to when it occurs exactly, if possible please share a video so that I can look into this issue, Thanks

Its work most of the time perfectly! but it bugged sometimes , check the specific code to get the bug report ,it is the main feature of your mod if it can't work no one use it so please fix it.

**Comment by Devilx86** [comment]
> > I just tested this now and it does not seem to be the case, cast vote seems to be working fine for me. Please verify and see if you can find a pattern as to when it occurs exactly, if possible please share a video so that I can look into this issue, Thanks
> 
> Its work most of the time perfectly! but it bugged sometimes , check the specific code to get the bug report ,it is the main feature of your mod if it can't work no one use it so please fix it.

Sorry I don't see any issues in the code, I believe this could be because of some mod the other player has on his end, maybe Anti Vote? or something like that but If you come accross this issue again please record a video and let me know, will close for now.
