### ISSUE TITLE
Want Start Without Players

### ISSUE THREAD

**Issue by PapaNoob63** [Devilx86/ImpostorModmenu#24]
I Want Feature Which Can Start The Match Without Players Its So Easy To Mod @Devilx86

**Comment by Redlything** [comment]
Why dont you join our discord and do it yourself then?

**Comment by PapaNoob63** [comment]
> Why dont you join our discord and do it yourself then?

already joined.

**Comment by Masters110** [comment]
Use freeplay

**Comment by Devilx86** [comment]
@PapaNoob63 I have made this but it results in a ban on the official among us server, so won't be adding this.
