### ISSUE TITLE
enable Tasks as Imp.

### ISSUE THREAD

**Issue by syncate** [Devilx86/ImpostorModmenu#27]
can you enable Tasks in Imposter mode?

**Comment by syncate** [comment]
@Devilx86 for notification 🥇

**Comment by amongX86** [comment]
> can you enable Tasks in Imposter mode?

There is actually no need to do tasks, you can just go to places where the map shows you have tasks and stand there for few seconds.
Why you shouldn't do tasks because task bar will fill and Crewmates win the match!
So it's just unnecessary feature in my opinion.
