### ISSUE TITLE
Can't inject

### ISSUE THREAD

**Issue by elohim121** [Devilx86/ImpostorModmenu#28]
Hi,
I'am using injectapk.sh to inject the impostormenu into amoungus but there is an error.

APK=/home/elohim/Desktop/apk/amoungus.apk
MODMENU_APK=/home/elohim/Desktop/apk/Impostor-v1.3.apk
OUTPUT=/home/elohim/Desktop/apk/amongus-impostor-v1.3.apk
KEYSTORE=
WDIR=/tmp/tmp.BDA9ZzyCnm

[+] Copying files

[+] Decompiling Impostor-v1.3.apk file
I: Using Apktool 2.4.1 on Impostor-v1.3.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/elohim/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

[+] Decompiling amoungus.apk file
I: Using Apktool 2.4.1 on amoungus.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/elohim/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

[+] Copying libraries
[+] Copying assets
[+] Copying smali files
[+] Injecting startup code
[+] Diffing code modifications:
116a117,118
    invoke-static \{p0\}, Lcom\/devilx86\/modmenu\/MenuMain;->initModMenu(Landroid\/content\/Context;)V

Updating Manifest
Diffing Manifest modifications:
10a11
     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"\/>
14a16
        <service android:name="com.devilx86.modmenu.MenuService" android:enabled="true" android:exported="false"\/>
38c40
 </manifest>
\ No newline at end of file
---
</manifest>

Baksmaling apk to /home/elohim/Desktop/apk/amongus-impostor-v1.3.apk
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,18] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,22] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,30] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,31] Error for input '/': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,40] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,41] Error for input '/': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,32] mismatched input 'devilx86' expecting OPEN_PAREN
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,49] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,50] Error for input '/': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,59] Error for input ';': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,82] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,83] Error for input '/': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,91] Error for input '\': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,92] Error for input '/': Invalid text
amoungus/smali/com/unity3d/player/UnityPlayerActivity.smali[117,100] Error for input ';': Invalid text
Could not smali file: com/unity3d/player/UnityPlayerActivity.smali
[+] Zip aligning APK
Unable to open 'unaligned.apk' as zip archive
mv: cannot stat 'aligned.apk': No such file or directory

[+] Unsigned APK Created: /home/elohim/Desktop/apk/amongus-impostor-v1.3.apk
[+] Signing /home/elohim/Desktop/apk/amongus-impostor-v1.3.apk
Unable to open '/home/elohim/Desktop/apk/amongus-impostor-v1.3.apk' for verification
Verifying alignment of /home/elohim/Desktop/apk/amongus-impostor-v1.3.apk (4)...
Keystore password for signer #1: 
Failed to load signer "signer #1"
java.io.FileNotFoundException: /home/elohim/keystore/ImpostorMenu.keystore (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadKeyStoreFromFile(ApkSignerTool.java:828)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:719)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:659)
	at com.android.apksigner.ApkSignerTool$SignerParams.access$500(ApkSignerTool.java:611)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:266)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
Unable to open '/home/elohim/Desktop/apk/amongus-impostor-v1.3.apk' for verification
Verifying alignment of /home/elohim/Desktop/apk/amongus-impostor-v1.3.apk (4)...
[+] Removed /tmp/tmp.BDA9ZzyCnm

How can i fix it ?

**Comment by Devilx86** [comment]
Duplicate, Please see this:
https://github.com/Devilx86/ImpostorModmenu/issues/9#issuecomment-707512727
