### ISSUE TITLE
Feature Request For V1.4

### ISSUE THREAD

**Issue by WiliamR** [Devilx86/ImpostorModmenu#29]
1.Hide Chat Button / Hide Chat Allways Visible
(Make a Button to Enable Or Disable it)

2.Enable Or Disable : See Ghost Feature
(make a button to enable or disable it)

3.Close Spesific Door (Choose Which Door We Want To Lock)

4.No Door Cooldown For Impostor (Including Other Sabotage)

5.Revive Yourself (Come Back Alive After Being Killed)

**Comment by PapaNoob63** [comment]
any sus that this i ready and to be come??

**Comment by Devilx86** [comment]
> 1.Hide Chat Button / Hide Chat Allways Visible
> (Make a Button to Enable Or Disable it)
> 
> 2.Enable Or Disable : See Ghost Feature
> (make a button to enable or disable it)
> 
> 3.Close Spesific Door (Choose Which Door We Want To Lock)
> 
> 4.No Door Cooldown For Impostor (Including Other Sabotage)
> 
> 5.Revive Yourself (Come Back Alive After Being Killed)

Hello, May I know why do you want to disable the chat button/see ghosts? Other players will not know about this anyway.

**Comment by DerWal** [comment]
Can you add a revive function?

**Comment by WiliamR** [comment]
> > 1.Hide Chat Button / Hide Chat Allways Visible
> > (Make a Button to Enable Or Disable it)
> > 2.Enable Or Disable : See Ghost Feature
> > (make a button to enable or disable it)
> > 3.Close Spesific Door (Choose Which Door We Want To Lock)
> > 4.No Door Cooldown For Impostor (Including Other Sabotage)
> > 5.Revive Yourself (Come Back Alive After Being Killed)
> 
> Hello, May I know why do you want to disable the chat button/see ghosts? Other players will not know about this anyway.

Sometimes im recording my gameplay , and The Chat Button Is Visible Making Me Looks like cheating. I just wanted to make it looks like Normal App From Playstore.

Thanks for Reviewing My Request man

**Comment by WiliamR** [comment]
> Can you add a revive function?

Axey Mods Have It , But Only Work When You Are Host
