### ISSUE TITLE
Max Light does not work, Player briefly walks through wall at the start of the game

### ISSUE THREAD

**Issue by Ankkii** [Devilx86/ImpostorModmenu#32]
1.Max lighting -  not working for me and when ever i clicked on the Max lighting screen started blinking - giving whitesh effect on screen again n again to fix this i need to restart the game 
2. Spoof message - when ever I'm using it I'm getting kicked out of game (i know they have updated server that's y its happing) 
3. Bug - Sometime even without activating any of the mod From mod menu . My playing is walking through the walls. 

At last - Thanks for your hard work . Keep it up .👌🏻

Update - Fake imposter  and Play Animation now start working  for me and to get a kill option if you r fake imposter you need click ones on sabtoge .

**Comment by Devilx86** [comment]
Hello these have been fixed in 1.5, source will come later, just fixing some more bugs, for now you can get the released APK from my youtube.
