### ISSUE TITLE
Weird State

### ISSUE THREAD

**Issue by RCCRAFT1** [Devilx86/ImpostorModmenu#38]
Hello!

There is a state in this APK where it asks you on the first startup to allow it to draw over other apps. 
I allow it to do this
When opened, the app flashes an image, then closes.
Basically, the app crashes
Any Idea of what to do to get it working?

**Comment by Devilx86** [comment]
Hello, Sorry I have never had this happen to me. I could try to fix it if you can give some more info like are you on an emulator or a device? What version? etc

**Comment by Devilx86** [comment]
> d, the app flashes an image, then closes.
> Basically, the app crashes
> Any Idea of what to do to get it working?

I am not sure but I think this has been fixed in 1.5
