### ISSUE TITLE
Allow more than 10 players on a custom server

### ISSUE THREAD

**Issue by jakovmarkovanovic** [Devilx86/ImpostorModmenu#40]
Break 10 players Limit [custom server]

Region Creator [Creative Region with special ip connect to custom server ]

**Comment by Milionerzy11** [comment]
Hey Good idea

**Comment by Ankkii** [comment]
Nice.  👌🏻

**Comment by Masters110** [comment]
No they will see that and block it in seconds

**Comment by jakovmarkovanovic** [comment]
> No they will see that and block it in seconds

how can i see the custom server you are hosting
https://github.com/Impostor/Impostor

**Comment by Masters110** [comment]
> > No they will see that and block it in seconds
> 
> how can i see the custom server you are hosting
> https://github.com/Impostor/Impostor
> and you can break the anti cheat function if you know how to programIng

L0Q

**Comment by Devilx86** [comment]
Hello Regarding this, someone else told me on discord a few days back to add a feature to change just "Max Player" count in game and it may help them with hosting more players in a custom server, So I have added this option but I have not tested if it works, if anyone could try and let me know that would be great! Once I fix the issues in 1.5 I will look into this.

**Comment by jakovmarkovanovic** [comment]
@Devilx86 is it possible to make multiple players choose the same color?

**Comment by Devilx86** [comment]
Yes on a custom server it is, I am actually working on this. The patches I had in the older version were not sufficient and I have made some more progress regarding this feature. 

However recently kill timer was patched so I just updated my mod menu to v1.6,.

**Comment by Devilx86** [comment]
Added in 1.8, there are some bugs but will fix them in the next updates.
