### ISSUE TITLE
Can't use hacks anymore. 

### ISSUE THREAD

**Issue by JackAttackCat** [Devilx86/ImpostorModmenu#41]
I want to use that spoof chat feature because it is the funniest one to me, and I can't use it or i get banned. Please please please find a way past this.

**Comment by Devilx86** [comment]
There is a way and I have seen people who have done it even with the new client update on Android and from what the common pattern of what the game looks like when they do this, I could think of how they are doing it however I have not spend enough time looking into it and trying it out etc. I am still fixing issues in v1.5. Also even if I figure it out and find the way they are doing it,  if its a serious issue I would report it to InnerSloth first if not I could release a version with Antiban which probably could be patched in like 2 to 3 hours of its release.
