### ISSUE TITLE
Mod not working 

### ISSUE THREAD

**Issue by Aloysius8** [Devilx86/ImpostorModmenu#44]
Hello, I downloaded this mod and I can see the icon also when playing the game... However none of the options work at all... I've tried restarting the game several times and still run into the same issue.

**Comment by Aloysius8** [comment]
Update: It's working now, but most functions you use will get you banned immediately.

**Comment by Masters110** [comment]
Because they added anti chest about 10 days ago. Hardly anything works

**Comment by Devilx86** [comment]
Apart from this, there is a new update now, I was supposed to release 1.5 today or tomorrow but I am going to port things to the new client now.

**Comment by Aloysius8** [comment]
Okay! Where can we find the new one? Will you be posting it? :)

**Comment by Devilx86** [comment]
Yes, will post it soon
