### ISSUE TITLE
Update plezz

### ISSUE THREAD

**Issue by Ankkii** [Devilx86/ImpostorModmenu#45]
Update to the latest version

**Comment by Devilx86** [comment]
Hey, I just updated to the latest version and removed things that result in a ban however there are some bugs now due to changes in the among us game code, will try to fix and release soon :)

**Comment by Ankkii** [comment]
Thanks buddy 😃

**Comment by Aloysius8** [comment]
@Devilx86 Will you be able to make the spoof chat available? Like we send messages as other people?

**Comment by savio2311** [comment]
Where can I download the new version

**Comment by Ankkii** [comment]
> Where can I download the new version

New updated mod is not released yet

**Comment by pokeyjojo** [comment]
wait so do you mean you will remove the stuff that bans you? or alter it so it doesn't
because the mod menu would have a lot less mods just curious

**Comment by Masters110** [comment]
> wait so do you mean you will remove the stuff that bans you? or alter it so it doesn't
> because the mod menu would have a lot less mods just curious

Its basically  self fake imposter kill and report. No one else sees them dead..


List of things that work 

Self tasks for you only ( any other =ban)

Fake imposter works half you can kill but only you see it useful for fake reporting. You can vent. And sabotage ( the sabotage menu doesn't work its only for you)

Max lighting works only  in the lobby

Colour cycler  works 

Being able to see who the imposter are works

Player speed works

No ads/ everything unlocked works

Lock all doors works



Everything else = ban

**Comment by Masters110** [comment]
> @Devilx86 Will you be able to make the spoof chat available? Like we send messages as other people?

No

**Comment by Aloysius8** [comment]
Welp, that basically wraps it up then.

**Comment by Masters110** [comment]
> Welp, that basically wraps it up then.

What did you expect they added a anti cheat.

**Comment by Devilx86** [comment]
Also Flip map and a couple of things. But yeah they added anti cheat and there is definintely a way around it, I have seen people do it and I could think of ways but have not looked into to it much yet.
