### ISSUE TITLE
1.3 still works without updating 

### ISSUE THREAD

**Issue by Masters110** [Devilx86/ImpostorModmenu#47]
Topic

**Comment by yj94** [comment]
which version？

**Comment by Devilx86** [comment]
Lol really?

**Comment by Masters110** [comment]
> Is it still working?

1.3 from here still works

**Comment by Devilx86** [comment]
Oh I see, Maybe they are just keeping it for a while just to give people time to update their game. Probably you will start getting the Game option mismatch issue in a couple of days.
