### ISSUE TITLE
1.3 not working on among us new version

### ISSUE THREAD

**Issue by abolfazleffati** [Devilx86/ImpostorModmenu#48]
ImpostorModmenu 1.3 not working on among us 20.10.22 & 20.11.4 

I tested but it didn't work

**Comment by abolfazleffati** [comment]
But it still works on version 20.9.9

> ImpostorModmenu 1.3 not working on among us 20.10.22 & 20.11.4
> 
> I tested but it didn't work

**Comment by Devilx86** [comment]
Hello, Please see my youtube, I have uploaded v1.5 there for the new client, I have not pushed the source code to git yet. I am still fixing a few bugs, some people on older device couldn't get it working and there were a couple of other bugs I was told about on discord.

**Comment by abolfazleffati** [comment]
When will we see the source code in the gate?

**Comment by abolfazleffati** [comment]
> Hello, Please see my youtube, I have uploaded v1.5 there for the new client, I have not pushed the source code to git yet. I am still fixing a few bugs, some people on older device couldn't get it working and there were a couple of other bugs I was told about on discord.

When will we see the source code in the gate?
