### ISSUE TITLE
Bạn có dự định update source impostor menu 1.5 in Github ?

### ISSUE THREAD

**Issue by khanhuypr** [Devilx86/ImpostorModmenu#52]
**Maybe for some reason you haven't updated v1.5 here, you plan to update it?**

**Comment by Devilx86** [comment]
Yes, will update in a couple of weeks after I add some more things. 1.4 had most of the fun things like Swap Player, Swap Player on murder etc. 1.5 is still buggy and there are some more things that are still being added.
