### ISSUE TITLE
Game bugging out after using "Wallhack" cheat in lobby

### ISSUE THREAD

**Issue by Philisonye** [Devilx86/ImpostorModmenu#53]
Apperantly, I've been using this hack for 30 mins. And already expiriencing some troubles. After playing in some lobbies Wallhack stopped working properly. After turning it on it will just freeze your screen. Reinstalling didn't helped.

**Comment by Magatsu-Iz** [comment]
Have you tried updating to ver. 1.5.1 of the hack?

**Comment by Philisonye** [comment]
I did, but it keeps crashing after the first use of wall hack

**Comment by Magatsu-Iz** [comment]
Thats odd, that doesnt happen to me. My game only crashes when I turn on the hacks before joining a game.

**Comment by Devilx86** [comment]
Old issue, fixed in the newer versions.
