### ISSUE TITLE
Mod installing

### ISSUE THREAD

**Issue by hCkERMaN** [Devilx86/ImpostorModmenu#59]
I really don't understand the how to download and use the mod menu but this is the best one I seen yet so maybe if you could make a video or go in further in detail about how to install and use that would be great.

**Comment by Devilx86** [comment]
1. Uninstall Among Us from your device.
2. Download the mod from the Mediafire/mega links (see my youtube/polarmods thread)
3. Open the APK once it finishes downloading to install.
