### ISSUE TITLE
Max Players [Host]

### ISSUE THREAD

**Issue by Aloysius8** [Devilx86/ImpostorModmenu#61]
Hello, 

Whenever I try to put more than 10 players it never works. It still only allows 10 people into the game. Am I doing something wrong? Thanks

**Comment by Devilx86** [comment]
Max players is visual only in <= 1.7 ;)

**Comment by Aloysius8** [comment]
I don't get it lol will there be an update in the future for it?

**Comment by Devilx86** [comment]
> I don't get it lol will there be an update in the future for it?

Yes.
