### ISSUE TITLE
How do you dumped all local type definitions from the type il2cpp library with IDA?

### ISSUE THREAD

**Issue by ghost** [Devilx86/ImpostorModmenu#68]

**Comment by Devilx86** [comment]
I used the following option:
File > Produce File > Create C Header

**Comment by ghost** [comment]
ok thanks

**Comment by ghost** [comment]
@Devilx86 I'm Create C Header With this option, but why there exporting only 116 local types? And there are no Among Us Classes (PlayerControl, PlayerPhysics, etc.)?

**Comment by ghost** [comment]
Thanks, all is fine, i just dumped library to c header file using IL2CPP Dumper.
