### ISSUE TITLE
19 Errors when building APK

### ISSUE THREAD

**Issue by ghost** [Devilx86/ImpostorModmenu#69]
I'm using Android Studio 3.6.1, and NDK v21d. But when i'm trying to build APK, im getting bunch of errors (19) in file libil2cpp.h

There are all of this errors:

![Скриншот 19-02-2021 22_55_46](https://user-images.githubusercontent.com/60845352/108554769-3ff14180-72fd-11eb-80f5-cba44519de51.jpg)
![Скриншот 19-02-2021 22_55_29](https://user-images.githubusercontent.com/60845352/108554777-42539b80-72fd-11eb-966b-b3cbe7e03fab.jpg)
![Скриншот 19-02-2021 22_54_57](https://user-images.githubusercontent.com/60845352/108554783-4384c880-72fd-11eb-92ca-a0dbad3dad58.jpg)
![Скриншот 19-02-2021 22_54_34](https://user-images.githubusercontent.com/60845352/108554792-454e8c00-72fd-11eb-84f9-7202f64a76eb.jpg)

**Comment by Devilx86** [comment]
I was compiling with NDK version=`19.2.5345600` at the time. From your previous issue I assume you have modified `libil2cpp.h` yourself.

The error messages indicate that you are missing declaration for `Elf32_Dyn` it also suggests that you rename it to `Elf32_Sym`. I am not sure what you are trying to achieve. But you could try removing `Elf32_Dyn` if you are not using it or declare it if you need it (as suggested by the compiler).
