### ISSUE TITLE
apktool: command not found

### ISSUE THREAD

**Issue by khanhuypr** [Devilx86/ImpostorModmenu#8]
how does apktool work
![Untitled](https://user-images.githubusercontent.com/34980250/95752285-fd25ba00-0cc9-11eb-9611-3fa981330851.png)

**Comment by Devilx86** [comment]
On the right side terminal it says `apktool not found` try running just `apktool` command from that environment instead of the script, you will most likely get the same error, if this is the case this has to do with you not having the location of apktool added to your Path variables.

**Comment by khanhuypr** [comment]
![image](https://user-images.githubusercontent.com/34980250/95753238-87bae900-0ccb-11eb-82bf-a4b114308372.png)

**Comment by khanhuypr** [comment]
how to add apktool to bash

**Comment by khanhuypr** [comment]
> how does apktool work
> ![Untitled](https://user-images.githubusercontent.com/34980250/95752285-fd25ba00-0cc9-11eb-9611-3fa981330851.png)
